#!/bin/sh

# get brew
if ! command -v brew >/dev/null; then
  echo "Installing Homebrew ..."
  curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install'
  export PATH="/usr/local/bin:$PATH"
fi

# get dependencies from brew
brew update --force
brew bundle --file=Brewfile || true

./start_docker
