#!/bin/sh

# get brew
if ! command -v brew >/dev/null; then
  echo "Installing Homebrew ..."
  curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install'
  export PATH="/usr/local/bin:$PATH"
fi

# get dependencies from brew
brew update --force
brew bundle --file=Brewfile || true

# kill all processes using port 5432
lsof -i :5432 | grep -ioh " \d\+ " | xargs kill -9


for i in ../*; do
  # iterate through folders in the parent path and build run docker
  if [ -d "$i" ];
  then
    cd $i
    # if there is a docker-compose.yml
    if [ -f docker-compose.yml ]; then
      # start the container
      docker-compose up -d
    fi
  fi
done
